//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentationRobot.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PresentationRobot.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Authentication に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Authentication_Category {
            get {
                return ResourceManager.GetString("Authentication_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Common_Category {
            get {
                return ResourceManager.GetString("Common_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If set, continue executing the remaining activities even if the current activity has failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_Description {
            get {
                return ResourceManager.GetString("ContinueOnError_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ContinueOnError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ContinueOnError_DisplayName {
            get {
                return ResourceManager.GetString("ContinueOnError_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_BackgroundColor_Description {
            get {
                return ResourceManager.GetString("DisplayMessage_BackgroundColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BackgroundColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_BackgroundColor_DisplayName {
            get {
                return ResourceManager.GetString("DisplayMessage_BackgroundColor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_BackgroundOpacity_Description {
            get {
                return ResourceManager.GetString("DisplayMessage_BackgroundOpacity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   BackgroundOpacity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_BackgroundOpacity_DisplayName {
            get {
                return ResourceManager.GetString("DisplayMessage_BackgroundOpacity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   display messages while runnunig the process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_Description {
            get {
                return ResourceManager.GetString("DisplayMessage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DisplayMessage に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_DisplayName {
            get {
                return ResourceManager.GetString("DisplayMessage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_FontSize_Description {
            get {
                return ResourceManager.GetString("DisplayMessage_FontSize_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FontSize に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_FontSize_DisplayName {
            get {
                return ResourceManager.GetString("DisplayMessage_FontSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_Image_Description {
            get {
                return ResourceManager.GetString("DisplayMessage_Image_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_Image_DisplayName {
            get {
                return ResourceManager.GetString("DisplayMessage_Image_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_IsFullWidth_Description {
            get {
                return ResourceManager.GetString("DisplayMessage_IsFullWidth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IsFullWidth に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_IsFullWidth_DisplayName {
            get {
                return ResourceManager.GetString("DisplayMessage_IsFullWidth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_Message_Description {
            get {
                return ResourceManager.GetString("DisplayMessage_Message_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Message に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_Message_DisplayName {
            get {
                return ResourceManager.GetString("DisplayMessage_Message_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_Position_Description {
            get {
                return ResourceManager.GetString("DisplayMessage_Position_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_Position_DisplayName {
            get {
                return ResourceManager.GetString("DisplayMessage_Position_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///    に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_TextColor_Description {
            get {
                return ResourceManager.GetString("DisplayMessage_TextColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TextColor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayMessage_TextColor_DisplayName {
            get {
                return ResourceManager.GetString("DisplayMessage_TextColor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Flying_Robot {
            get {
                object obj = ResourceManager.GetObject("Flying_Robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Input_Category {
            get {
                return ResourceManager.GetString("Input_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Listening_Robot {
            get {
                object obj = ResourceManager.GetObject("Listening_Robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Options_Category {
            get {
                return ResourceManager.GetString("Options_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Output_Category {
            get {
                return ResourceManager.GetString("Output_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Processing_Robot {
            get {
                object obj = ResourceManager.GetObject("Processing_Robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Receiving_Robot {
            get {
                object obj = ResourceManager.GetObject("Receiving_Robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Recorder_Robot {
            get {
                object obj = ResourceManager.GetObject("Recorder_Robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   型 System.Drawing.Bitmap のローカライズされたリソースを検索します。
        /// </summary>
        public static System.Drawing.Bitmap Searching_Robot {
            get {
                object obj = ResourceManager.GetObject("Searching_Robot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Specifies the amount of time (in milliseconds) to wait for the activity to run before an error is thrown. The default value is 60000 (1 minute). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Description {
            get {
                return ResourceManager.GetString("Timeout_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (milliseconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_DisplayName {
            get {
                return ResourceManager.GetString("Timeout_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The activity timed out and was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Timeout_Error {
            get {
                return ResourceManager.GetString("Timeout_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value either for {0} or {1}, but not both. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationExclusiveProperties_Error {
            get {
                return ResourceManager.GetString("ValidationExclusiveProperties_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide values for both {0} and {1}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationOverloadGroup_Error {
            get {
                return ResourceManager.GetString("ValidationOverloadGroup_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cannot be used outside of a {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationScope_Error {
            get {
                return ResourceManager.GetString("ValidationScope_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please provide a value for {0}. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ValidationValue_Error {
            get {
                return ResourceManager.GetString("ValidationValue_Error", resourceCulture);
            }
        }
    }
}
